-- ============================================================
-- seed_countries.sql — countries 참조 테이블 시드 (ISO 3166-1 alpha-2)
-- 정본 목록: code/api/nationalities.csv (199개국). flag_filename은 프론트 전용이라 DB에 넣지 않는다.
-- 생성: scratchpad/gen_seed.py (nationalities.csv → 이 파일). 손으로 고치지 말고 CSV를 고쳐 재생성.
-- 멱등: ON CONFLICT 업서트라 여러 번 실행 안전. 적용: psql "$DB" -f db/seed_countries.sql
-- ============================================================
INSERT INTO countries (code, name_ko, name_en) VALUES
  ('AD', '안도라', 'Andorra'),
  ('AE', '아랍에미리트', 'United Arab Emirates'),
  ('AF', '아프가니스탄', 'Afghanistan'),
  ('AG', '앤티가 바부다', 'Antigua and Barbuda'),
  ('AL', '알바니아', 'Albania'),
  ('AM', '아르메니아', 'Armenia'),
  ('AO', '앙골라', 'Angola'),
  ('AR', '아르헨티나', 'Argentina'),
  ('AT', '오스트리아', 'Austria'),
  ('AU', '오스트레일리아', 'Australia'),
  ('AW', '아루바', 'Aruba'),
  ('AZ', '아제르바이잔', 'Azerbaijan'),
  ('BA', '보스니아 헤르체고비나', 'Bosnia and Herzegovina'),
  ('BB', '바베이도스', 'Barbados'),
  ('BD', '방글라데시', 'Bangladesh'),
  ('BE', '벨기에', 'Belgium'),
  ('BF', '부르키나파소', 'Burkina Faso'),
  ('BG', '불가리아', 'Bulgaria'),
  ('BH', '바레인', 'Bahrain'),
  ('BI', '부룬디', 'Burundi'),
  ('BJ', '베냉', 'Benin'),
  ('BN', '브루나이', 'Brunei'),
  ('BO', '볼리비아', 'Bolivia'),
  ('BR', '브라질', 'Brazil'),
  ('BS', '바하마', 'Bahamas'),
  ('BT', '부탄', 'Bhutan'),
  ('BV', '부베섬', 'Bouvet Island'),
  ('BW', '보츠와나', 'Botswana'),
  ('BY', '벨라루스', 'Belarus'),
  ('BZ', '벨리즈', 'Belize'),
  ('CA', '캐나다', 'Canada'),
  ('CD', '콩고 민주공화국', 'DR Congo'),
  ('CF', '중앙아프리카 공화국', 'Central African Republic'),
  ('CG', '콩고 공화국', 'Republic of the Congo'),
  ('CH', '스위스', 'Switzerland'),
  ('CI', '코트디부아르', 'Ivory Coast'),
  ('CL', '칠레', 'Chile'),
  ('CM', '카메룬', 'Cameroon'),
  ('CN', '중국', 'China'),
  ('CO', '콜롬비아', 'Colombia'),
  ('CR', '코스타리카', 'Costa Rica'),
  ('CU', '쿠바', 'Cuba'),
  ('CV', '카보베르데', 'Cape Verde'),
  ('CW', '퀴라소', 'Curacao'),
  ('CY', '키프로스', 'Cyprus'),
  ('CZ', '체코', 'Czechia'),
  ('DE', '독일', 'Germany'),
  ('DJ', '지부티', 'Djibouti'),
  ('DK', '덴마크', 'Denmark'),
  ('DM', '도미니카 연방', 'Dominica'),
  ('DO', '도미니카 공화국', 'Dominican Republic'),
  ('DZ', '알제리', 'Algeria'),
  ('EC', '에콰도르', 'Ecuador'),
  ('EE', '에스토니아', 'Estonia'),
  ('EG', '이집트', 'Egypt'),
  ('ER', '에리트레아', 'Eritrea'),
  ('ES', '스페인', 'Spain'),
  ('ET', '에티오피아', 'Ethiopia'),
  ('FI', '핀란드', 'Finland'),
  ('FJ', '피지', 'Fiji'),
  ('FM', '미크로네시아', 'Micronesia'),
  ('FR', '프랑스', 'France'),
  ('GA', '가봉', 'Gabon'),
  ('GB', '영국', 'United Kingdom'),
  ('GD', '그레나다', 'Grenada'),
  ('GE', '조지아', 'Georgia'),
  ('GH', '가나', 'Ghana'),
  ('GM', '감비아', 'Gambia'),
  ('GN', '기니', 'Guinea'),
  ('GQ', '적도기니', 'Equatorial Guinea'),
  ('GR', '그리스', 'Greece'),
  ('GT', '과테말라', 'Guatemala'),
  ('GW', '기니비사우', 'Guinea-Bissau'),
  ('GY', '가이아나', 'Guyana'),
  ('HK', '홍콩', 'Hong Kong'),
  ('HN', '온두라스', 'Honduras'),
  ('HR', '크로아티아', 'Croatia'),
  ('HT', '아이티', 'Haiti'),
  ('HU', '헝가리', 'Hungary'),
  ('ID', '인도네시아', 'Indonesia'),
  ('IE', '아일랜드', 'Ireland'),
  ('IL', '이스라엘', 'Israel'),
  ('IN', '인도', 'India'),
  ('IQ', '이라크', 'Iraq'),
  ('IR', '이란', 'Iran'),
  ('IS', '아이슬란드', 'Iceland'),
  ('IT', '이탈리아', 'Italy'),
  ('JM', '자메이카', 'Jamaica'),
  ('JO', '요르단', 'Jordan'),
  ('JP', '일본', 'Japan'),
  ('KE', '케냐', 'Kenya'),
  ('KG', '키르기스스탄', 'Kyrgyzstan'),
  ('KH', '캄보디아', 'Cambodia'),
  ('KI', '키리바시', 'Kiribati'),
  ('KM', '코모로', 'Comoros'),
  ('KR', '대한민국', 'South Korea'),
  ('KW', '쿠웨이트', 'Kuwait'),
  ('KZ', '카자흐스탄', 'Kazakhstan'),
  ('LA', '라오스', 'Laos'),
  ('LB', '레바논', 'Lebanon'),
  ('LC', '세인트루시아', 'Saint Lucia'),
  ('LI', '리히텐슈타인', 'Liechtenstein'),
  ('LK', '스리랑카', 'Sri Lanka'),
  ('LR', '라이베리아', 'Liberia'),
  ('LS', '레소토', 'Lesotho'),
  ('LT', '리투아니아', 'Lithuania'),
  ('LU', '룩셈부르크', 'Luxembourg'),
  ('LV', '라트비아', 'Latvia'),
  ('LY', '리비아', 'Libya'),
  ('MA', '모로코', 'Morocco'),
  ('MC', '모나코', 'Monaco'),
  ('MD', '몰도바', 'Moldova'),
  ('ME', '몬테네그로', 'Montenegro'),
  ('MG', '마다가스카르', 'Madagascar'),
  ('MH', '마셜 제도', 'Marshall Islands'),
  ('MK', '북마케도니아', 'North Macedonia'),
  ('ML', '말리', 'Mali'),
  ('MM', '미얀마', 'Myanmar'),
  ('MN', '몽골', 'Mongolia'),
  ('MR', '모리타니', 'Mauritania'),
  ('MT', '몰타', 'Malta'),
  ('MU', '모리셔스', 'Mauritius'),
  ('MV', '몰디브', 'Maldives'),
  ('MW', '말라위', 'Malawi'),
  ('MX', '멕시코', 'Mexico'),
  ('MY', '말레이시아', 'Malaysia'),
  ('MZ', '모잠비크', 'Mozambique'),
  ('NA', '나미비아', 'Namibia'),
  ('NE', '니제르', 'Niger'),
  ('NG', '나이지리아', 'Nigeria'),
  ('NI', '니카라과', 'Nicaragua'),
  ('NL', '네덜란드', 'Netherlands'),
  ('NO', '노르웨이', 'Norway'),
  ('NP', '네팔', 'Nepal'),
  ('NR', '나우루', 'Nauru'),
  ('NZ', '뉴질랜드', 'New Zealand'),
  ('OM', '오만', 'Oman'),
  ('PA', '파나마', 'Panama'),
  ('PE', '페루', 'Peru'),
  ('PG', '파푸아뉴기니', 'Papua New Guinea'),
  ('PH', '필리핀', 'Philippines'),
  ('PK', '파키스탄', 'Pakistan'),
  ('PL', '폴란드', 'Poland'),
  ('PS', '팔레스타인', 'Palestine'),
  ('PT', '포르투갈', 'Portugal'),
  ('PW', '팔라우', 'Palau'),
  ('PY', '파라과이', 'Paraguay'),
  ('QA', '카타르', 'Qatar'),
  ('RO', '루마니아', 'Romania'),
  ('RS', '세르비아', 'Serbia'),
  ('RU', '러시아', 'Russia'),
  ('RW', '르완다', 'Rwanda'),
  ('SA', '사우디아라비아', 'Saudi Arabia'),
  ('SB', '솔로몬 제도', 'Solomon Islands'),
  ('SC', '세이셸', 'Seychelles'),
  ('SD', '수단', 'Sudan'),
  ('SE', '스웨덴', 'Sweden'),
  ('SG', '싱가포르', 'Singapore'),
  ('SI', '슬로베니아', 'Slovenia'),
  ('SK', '슬로바키아', 'Slovakia'),
  ('SL', '시에라리온', 'Sierra Leone'),
  ('SM', '산마리노', 'San Marino'),
  ('SN', '세네갈', 'Senegal'),
  ('SO', '소말리아', 'Somalia'),
  ('SR', '수리남', 'Suriname'),
  ('SS', '남수단', 'South Sudan'),
  ('ST', '상투메 프린시페', 'Sao Tome and Principe'),
  ('SV', '엘살바도르', 'El Salvador'),
  ('SX', '신트마르턴', 'Sint Maarten'),
  ('SY', '시리아', 'Syria'),
  ('SZ', '에스와티니', 'Eswatini'),
  ('TD', '차드', 'Chad'),
  ('TG', '토고', 'Togo'),
  ('TH', '태국', 'Thailand'),
  ('TJ', '타지키스탄', 'Tajikistan'),
  ('TL', '동티모르', 'Timor-Leste'),
  ('TM', '투르크메니스탄', 'Turkmenistan'),
  ('TN', '튀니지', 'Tunisia'),
  ('TO', '통가', 'Tonga'),
  ('TR', '튀르키예', 'Turkey'),
  ('TT', '트리니다드 토바고', 'Trinidad and Tobago'),
  ('TV', '투발루', 'Tuvalu'),
  ('TZ', '탄자니아', 'Tanzania'),
  ('UA', '우크라이나', 'Ukraine'),
  ('UG', '우간다', 'Uganda'),
  ('US', '미국', 'United States'),
  ('UY', '우루과이', 'Uruguay'),
  ('UZ', '우즈베키스탄', 'Uzbekistan'),
  ('VA', '바티칸 시국', 'Vatican City (Holy See)'),
  ('VC', '세인트빈센트 그레나딘', 'Saint Vincent and the Grenadines'),
  ('VE', '베네수엘라', 'Venezuela'),
  ('VI', '미국령 버진아일랜드', 'U.S. Virgin Islands'),
  ('VN', '베트남', 'Vietnam'),
  ('VU', '바누아투', 'Vanuatu'),
  ('WS', '사모아', 'Samoa'),
  ('YE', '예멘', 'Yemen'),
  ('ZA', '남아프리카 공화국', 'South Africa'),
  ('ZM', '잠비아', 'Zambia'),
  ('ZW', '짐바브웨', 'Zimbabwe')
ON CONFLICT (code) DO UPDATE SET
  name_ko = EXCLUDED.name_ko,
  name_en = EXCLUDED.name_en;
