package shinhan.fibri.ieum.main.admin.audit.domain;

public enum AdminAuditAction {
	USER_SANCTION_CREATED,
	USER_ACTIVATED,
	USER_ROLE_CHANGED,
	REPORT_CONFIRMED,
	REPORT_DISMISSED,
	INQUIRY_ANSWERED,
	KNOWLEDGE_RELATION_APPROVED,
	KNOWLEDGE_RELATION_REJECTED,
	USER_PROMOTED_TO_ADMIN,
	QUESTION_UPDATED,
	MEETING_UPDATED,
	QUESTION_HARD_DELETED,
	MEETING_HARD_DELETED
}
